server:
  port: 8769
#====================================================================== spring-配置 =====================================#
spring:
  profiles:
    active: jdbc
  application:
    name: Lux-ConfigService
  datasource:
    url: jdbc:mysql://10.1.241.152:3306/gta_ebd?serverTimezone=UTC&useSSL=false
    username: root
    password: root152
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc: true
spring.cloud.config.server.jdbc.sql: SELECT * from sys_config_properties where application=? and `profile`=? and `label`=?


#====================================================================== sql  数据库配置=====================================#
#  SET NAMES utf8mb4;
#  SET FOREIGN_KEY_CHECKS = 0;
#
#  -- ----------------------------
#  -- Table structure for sys_config_properties
#  -- ----------------------------
#  DROP TABLE IF EXISTS `sys_config_properties`;
#  CREATE TABLE `sys_config_properties`  (
#  `id` bigint(20) NOT NULL AUTO_INCREMENT,
#  `paramName` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '参数名',
#  `key` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '键',
#  `value` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '值',
#  `application` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '应用名称',
#  `isEnable` int(11) DEFAULT 0 COMMENT '是否启用 0:启用 1:禁用',
#  `profile` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '环境',
#  `label` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '分支',
#  `createTime` datetime(0) DEFAULT NULL COMMENT '创建时间',
#  `createBy` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
#  `updateTime` datetime(0) DEFAULT NULL COMMENT '修改时间',
#  `updateBy` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修复人',
#  PRIMARY KEY (`id`) USING BTREE
#  ) ENGINE = InnoDB AUTO_INCREMENT = 39 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;
#
#  SET FOREIGN_KEY_CHECKS = 1;



#  -- 服务 	Lux-account
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '单点登陆配置-CAS服务器', 'lux.sysproperties.casConfig.serverUrl', 'http://zhxy.edu.gtafe.com', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '单点登陆配置-项目地址', 'lux.sysproperties.casConfig.projectUrl', 'http://10.1.20.58:8100/zlbzxt/account', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '单点登陆配置-前端部署地址', 'lux.sysproperties.casConfig.redirectUrl', 'http://10.1.136.38:9101/#/sslogin', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '单点登陆配置-是否启用CAS认证', 'lux.sysproperties.casConfig.isEnable', 'false', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '登陆配置-退出配置', 'lux.sysproperties.callbackUrl', 'http://10.1.136.38:9101/#/login', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '消息中心配置-部署地址', 'lux.sysproperties.AgreementServiceConfig.messageCenterUrl', '10.1.136.38', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '消息中心配置-部署地址-端口号', 'lux.sysproperties.AgreementServiceConfig.port', '8899', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '消息中心配置-部署地址-消息长度', 'lux.sysproperties.AgreementServiceConfig.maxLength', '600', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'redis配置-地址', 'spring.redis.host', '10.1.136.38', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'redis配置-默认数据库', 'spring.redis.database', '0', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'redis配置-端口', 'spring.redis.port', '6379', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'redis配置-密码', 'spring.redis.password', NULL, 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '注册中心配置-地址', 'eureka.client.serviceUrl.defaultZone', 'http://gtanihao:123456@10.1.136.38:9100/zlbzxt/eureka/', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( '注册中心配置-当前服务部署地址', 'eureka.instance.ipAddress', '10.1.136.38', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'UC认证配置-部署地址', 'uc-apiconfig.url', 'http://10.1.135.40:5020', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'UC认证配置-加密秘钥', 'uc-apiconfig.signature', 'ky6xbsOp1UotNvz3H7fI', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#  INSERT INTO `gta_ebd`.`sys_config_properties`( `paramName`, `key`, `value`, `application`, `isEnable`, `profile`, `label`, `createTime`, `createBy`, `updateTime`, `updateBy`) VALUES ( 'UC认证配置-产品ID', 'uc-apiconfig.appId', 'OhtZG', 'Lux-account', NULL, 'dev', 'master', NULL, NULL, NULL, '');
#