
#====================================================================== Server-配置 ================#
server:
  port: 8769
  servlet:
    context-path: /jhome
  tomcat:
    uri-encoding: UTF-8
#====================================================================== spring-配置 =====================================#
spring:
  profiles:
    active: jdbc
  application:
    name: Lux-ConfigService
  datasource:
    url: jdbc:mysql://10.1.241.152:3306/gta_ebd?serverTimezone=UTC&useSSL=false
    username: root
    password: root152
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc: true
  redis:
    host: 10.1.136.38
    database: 0
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active:  1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.cloud.config.server.jdbc.sql: SELECT `key`,`value` from sys_config_properties  where application=? and `profile`=? and `label`=?
authorizationCode: Sqm