#======================================#
#========== com.nettyServer.Server settings ===========#
#======================================#
server:
  port: 8103
  servlet:
    context-path: /jhome
  tomcat:
    uri-encoding: UTF-8

#myspcloud:
#  item:
#    url: http://daxunihao:123456@127.0.0.1:8100/jhome/eureka/ # http://127.0.0.1:8081/item/


#========================================#
#============= 数据库配置地址 =============#
#========== Spring 基础配置信息 ===========#
#=========================================#
spring:
  # 应用程序名称
  application:
    name: jhome-Pay
  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default
  # 打印横幅
  main:
    bannerMode: "CONSOLE"

#=========================================#
#===============  日志配置 ===========#
#=========================================#
#logging:
#  config: classpath:/config/logback-spring.xml

#=========================================#
#========== Shrio 基础配置信息 ===========#
#=========================================#


#=========================================#
#========== mybase 基础配置信息 ===========#
#=========================================#

#=========================================#
#========== thymeleaf 基础配置信息 ========#
#=========================================#

#=========================================#
#================ 分页配置 ================#
#=========================================#
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#=========================================#
#============= 消息队列服务器地址  ========#
#=========================================#

#  ->->->->->->->->->->->->->->->->->->->-> 服务提供者 ->->->->->->->->->->->->->->->->->->->->
#=========================================#
#================ eureka配置 ================#
#=========================================#
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://daxunihao:123456@127.0.0.1:9100/jhome/eureka/,http://daxunihao:123456@127.0.0.1:9200/jhome/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心http://127.0.0.1:8100/jhome/eureka
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}---${server.port} 支付服务提供者 #指定实例id
